### ISSUE TITLE
Support for gatsby V3

### ISSUE THREAD

**Issue by hemant-tw** [Debens/gatsby-plugin-scss-typescript#24]
Does it work with Gatsby v3? I am trying to use it with the latest version of Gatsby(3.3.0) but The styles are not getting reflected in the DOM.

**Comment by nwehner** [comment]
Turns out I spoke too soon when I thought the alpha was working, sorry! The types indeed get generated, but because of the disabled tree shaking due to the TeamSupercell bug, Webpack can't find the styles. If you don't disable tree shaking, then Webpack is able to append the styles just fine, but the TS compiler can't find any type definitions. 

I'm trying to figure out what's going on with the styles not being applied when tree-shaking is disabled. So far no luck :(

**Comment by KoltesDigital** [comment]
I tried to upgrade last week and I'm having some troubles as well, wasn't sure where it came from; now that I've read this issue it may be the cause. The problem I have is with SSR only. `gatsby develop` is fine. However `gatsby build` produces HTML files where the class names are removed. So for visitors, the first page they open has broken styles, but as they navigate in the same tab, other pages as fine.

In `gatsby-config.js` I have this plugin entry:

```js
		{
			options: {
				cssLoaderOptions: {
					esModule: false,
					modules: {
						namedExport: false,
					},
				},
			},
			resolve: 'gatsby-plugin-scss-typescript',
		},
```

**Comment by nwehner** [comment]
I think the problem is that the `@teamsupercell/typings-for-css-modules-loader` module no longer works with the `resolve-url-loader` module because the latter doesn't correctly map the location of the style any longer. I'm testing a switch over to the `dts-css-modules-loader` module, but Webpack is currently throwing errors saying it can't find the css or sass loaders :'(

**Comment by nwehner** [comment]
I was finally able to get Webpack to build everything together locally :-D

I've created a PR [https://github.com/Debens/gatsby-plugin-scss-typescript/pull/25](https://github.com/Debens/gatsby-plugin-scss-typescript/pull/25) with that code. However, I haven't been able to get the included tests to pass.

**Comment by Debens** [comment]
I've fixed up the specs, commit linting, and the commit hooks. Your changes should be in the alpha channel now

`yarn add gatsby-plugin-scss-typescript@alpha`

**Comment by KoltesDigital** [comment]
Thanks for your work.

I've upgraded to this version, but the built pages still do not contain class names. Should I change something in gatsby-config.js? Any way I can give you useful info?

**Comment by nwehner** [comment]
I'm certainly stumped. I upgraded to the alpha release, too, and I'm back to getting the same "attempted import" errors as before. 

However, I published my forked codebase to NPM (which should be identical given the approved PR), and I *do* get all the types and classes and styles exported just fine. Gatsby should be running the same code with either module...

The only thing I can think of, just because it happens to me all the time, is that maybe NPM didn't properly build the latest release? Maybe it's still using the cached, compiled JS from the previous TypeScript compilation? Might be worth a Hail-Mary just to try doing another round of `tsc && webpack` and publishing a new alpha release from that.

**Comment by KoltesDigital** [comment]
The commit @Debens made two days ago didn't reach publishing: https://github.com/Debens/gatsby-plugin-scss-typescript/runs/2474012169

**Comment by Debens** [comment]
Sorry folks, this is why you don't just push and walk away!

The issue was some bad package upgrades, mainly the tslint updates, that are not compatible with node 11. God knows why the CI runs under node 11 as it's not a LTS version, but rather than upgrading all the environment tools I've reverted the non-required dev tools changes.

I'd much rather be removing tslint in the future as eslint actively supports TS ever since babel got a TS parser ages ago. But this isn't in the scope of this issue

Any who, the package is now deploying to the alpha channel!

I've not had time to test the result of these changes myself yet, so thank you all for being active in solving these issues yourselves. There is also an example repository where it would be useful to update to guide others in setup and be a basis to demonstrate these sorts of issues in future issues.

**Comment by KoltesDigital** [comment]
I've upgraded (5.1.1-alpha-331.0) and now both develop and SSR modes seem to work fine. I had to remove the config options, with them the plugin was not generating the class names. Thanks a lot!

**Comment by nemophrost** [comment]
FWIW, I upgraded to 5.1.1-alpha-331.0 and when I run `gatsby develop` it wipes out all the .d.ts file content for my scss modules. I tries using the plugin without any options and with:
```
{
  options: {
    cssLoaderOptions: {
      esModule: false,
      modules: {
        namedExport: false,
      },
    },
  },
  resolve: 'gatsby-plugin-scss-typescript',
},
```
with the same results.

**Comment by nwehner** [comment]
This is definitely a perplexing issue, that's for sure! Two weeks ago, everything worked fine. And now for the same site, I keep getting TSC errors that the `styles.module.scss` file isn't a module. 

The same code works 100% fine for me, though, if I put it in `gatsby-node.js` file. 

Try setting your `gatsby-node.js` config like:
`exports.onCreateWebpackConfig = ({ actions, plugins, rules }) => {
const useCss = rules.css().use;
	const useCssModules = rules.cssModules().use;
	const sassLoader = {
		loader: "sass-loader",
		options: {
			sourceMap: true
		},
	};
	const typeLoader = {
		loader: "dts-css-modules-loader",
		options: {
			namedExport: true
		}
	};
	const sassLoaders = [ ...useCss, sassLoader ];
	const typeLoaders = [ typeLoader, ...useCssModules, sassLoader ];

	actions.setWebpackConfig({
		module: {
			rules: [
				{
					oneOf: [
						{
							test: /\.module\.s(a|c)ss$/,
							use: typeLoaders,
						},
						{
							test: /\.s(a|c)ss$/,
							use: sassLoaders,
						},
					],
				},
			],
		},
		optimization: {
			minimizer: [plugins.minifyCss()],
		},
		plugins: [
			plugins.extractText(),
			plugins.ignore(/css\.d\.ts$/),
  	]
	});
}`

**Comment by KoltesDigital** [comment]
If I remember correctly, I had also issues in develop mode. After removing the options in _gatsby-config.js_ and running `gatsby clean && gatsby build` the develop mode was working. I suppose that there were significant changes to caching techniques in v3 to improve build times, but it may mess with the plugin. Also note the typing files will only be generated when a page that uses them is requested, again for speed I suppose, I vaguely remember that before they were all generated upfront.

**Comment by nwehner** [comment]
Just made a quick example at [https://github.com/nwehner/gatsbyScssTypeScriptExample](https://github.com/nwehner/gatsbyScssTypeScriptExample)

**Comment by ffMathy** [comment]
Any news on this?

**Comment by Debens** [comment]
Looks like this has gone a little stale and needs some fresh information to get things going again. 

Thanks for providing an example repo, can I just check that this is an example of a working repo where you've implemented what you believe to be a solution to the issue? 

Would it be possible to provide an example of a state where the current alpha, `5.1.1-alpha-345.0`, is exhibiting the described issue of declaration files going missing? I really appreciate the time to create your example and I've check this out to see it behaves as expected, however, it's hard to track down a bug in a repo that doesn't have the bug 🐛 

If you're looking for a base to start from, I suggest using this working example, [gatsby-plugin-typescript-scss-modules-example](https://github.com/Debens/gatsby-plugin-typescript-scss-modules-example), that I use as a showcase.

**Comment by DuneArchitect** [comment]
So before I bang my head into this more... has anyone successfully gotten this plugin working with Gatsby v3?

**Comment by nemophrost** [comment]
> So before I bang my head into this more... has anyone successfully gotten this plugin working with Gatsby v3?

FWIW, I ended switching to gatsby-plugin-sass + gatsby-plugin-dts-css-modules

**Comment by DuneArchitect** [comment]
> FWIW, I ended switching to gatsby-plugin-sass + gatsby-plugin-dts-css-modules

Thank you, this is the only thing that worked for me so far
